# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-11 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=500)),
                ('Teacher_name', models.CharField(max_length=500)),
                ('course_logo', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_title', models.CharField(max_length=250)),
                ('lecture_video', models.FileField(upload_to='')),
                ('albums', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinetut.Courses')),
            ],
        ),
    ]
